# Generated by Django 3.2.18 on 2023-03-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='班级ID')),
                ('grade_number', models.IntegerField(verbose_name='班级号')),
                ('college_id', models.CharField(max_length=20, verbose_name='学院ID')),
                ('major_id', models.CharField(max_length=20, verbose_name='专业ID')),
                ('year', models.IntegerField(verbose_name='届号')),
                ('teach_id', models.CharField(max_length=20, verbose_name='班主任ID')),
                ('count', models.IntegerField(verbose_name='人数')),
                ('content', models.TextField(blank=True, max_length=256, verbose_name='备注')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'gdut_grade',
            },
        ),
    ]
