# Generated by Django 3.2.18 on 2023-03-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach_research_office',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='教研室ID')),
                ('college_id', models.CharField(max_length=20, verbose_name='学院ID')),
                ('count', models.IntegerField(verbose_name='可容纳人数')),
                ('location', models.CharField(max_length=100, unique=True, verbose_name='地理位置')),
                ('content', models.TextField(blank=True, max_length=256, verbose_name='备注')),
            ],
            options={
                'verbose_name': '教研室',
                'verbose_name_plural': '教研室',
                'db_table': 'gdut_teach_research_office',
            },
        ),
    ]
