# Generated by Django 3.2.18 on 2023-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_teach_research_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False, verbose_name='班级ID'),
        ),
        migrations.AlterField(
            model_name='teach_research_office',
            name='id',
            field=models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False, verbose_name='教研室ID'),
        ),
    ]
