# Generated by Django 3.2.18 on 2023-03-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学院ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='学院名')),
                ('dean_id', models.CharField(max_length=20, verbose_name='院长ID')),
                ('content', models.TextField(blank=True, max_length=256, verbose_name='备注')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
                'db_table': 'gdut_college',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='专业ID')),
                ('name', models.CharField(max_length=50, verbose_name='专业名称')),
                ('college_id', models.CharField(max_length=20, verbose_name='学院ID')),
                ('content', models.TextField(blank=True, max_length=256, verbose_name='备注')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
                'db_table': 'gdut_major',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('grade_id', models.CharField(max_length=20, verbose_name='班级ID')),
                ('content', models.TextField(blank=True, max_length=256, verbose_name='备注')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'gdut_student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='教师号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('college_id', models.CharField(max_length=20, verbose_name='学院ID')),
                ('content', models.TextField(blank=True, max_length=256, verbose_name='备注')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'gdut_teacher',
            },
        ),
    ]
