# Generated by Django 3.2.18 on 2023-03-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmts', '0006_alter_major_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='college_id',
            field=models.IntegerField(verbose_name='学院ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_id',
            field=models.IntegerField(verbose_name='班级ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='college_id',
            field=models.IntegerField(verbose_name='学院ID'),
        ),
    ]
